name: Deploy MkDocs
on:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs
          # Se você usa o tema material, descomente a linha abaixo:
          # pip install mkdocs-material 

      - name: Deploy to GH Pages
        run: mkdocs gh-deploy --force