site_name: UrbIFES
nav:
  - Home: index.md
  - Problema: problema.md
  - Publico-Alvo: pa.md
  - Solução: solucao.md
  - Concorrentes: concorrentes.md
  - Indicadores de Sucesso: indicadores.md
  - Oportunidades: oportunidades.md
theme: readthedocs